### ISSUE TITLE
Add SRT barcodes and put them on separate lines in qbeds

### ISSUE THREAD

**Issue by marialexandra16** [cmatKhan/callingCardsTools#7]
### Description of feature

SRT barcodes should be listed in the qbed file, and different barcodes should be put on different lines.

**Comment by cmatKhan** [comment]
This is going to end up getting hard-coded in (rather than as an option to the user to choose the annotation, and whether it is added to the qbed), at least for the time being. It just requires adding another loop here over the annotation field:

https://github.com/cmatKhan/callingCardsTools/blob/1a6e147ea6882684ac1d1814ba8716b3b7c4bf7d/callingcardstools/Alignment/mammals/Qbed.py#L152

**Comment by cmatKhan** [comment]
fixed in proposed v1.1.0. requested real data for ease of testing

**Comment by cmatKhan** [comment]
done in v1.1.0
