### ISSUE TITLE
Sort qbed chromosomes in numerical order (lower priority)

### ISSUE THREAD

**Issue by marialexandra16** [cmatKhan/callingCardsTools#8]
### Description of feature

Sort chromosomes as 1, 2, 3, etc., and sort coordinates within them

**Comment by cmatKhan** [comment]
I'll make a passing attempt at this. There are so many different formats (1, 2, 3, chr1, 2, 3, NC1101213.1, ...) that this is more annoying than it should be.

Right now, for some reason chr11, chr12, ... are sorting before chr1, chr2, ... . I'll see if I can do something about that.

**Comment by cmatKhan** [comment]
Another reason this happens is because in the pipeline, for mammals starting at the fastq stage, the reads are split into parts for parallelization. The order in which the parts gets combined can be random.

One option would be to add a `sort` module which runs bedtools sort or something like that. But, that is one more software in the pipeline. It is also not unusual to have to sort the output of a given process (eg aligning) prior to doing something with it. So, I'm going to call this out of scope.
